//! Pure conversation-topic lookup over the curated Mob/structure dictionary.
//! A dictionary match is a candidate, never evidence of presence. Normal chat
//! ranks by the player's words first and adds observed flags only afterwards.
use crate::entry_catalog::{HOSTILE, NEUTRAL, PASSIVE, STRUCTURES};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::{
    collections::{HashMap, HashSet},
    sync::LazyLock,
};

#[derive(Deserialize)]
struct Rules {
    field_weights: HashMap<String, f64>,
    min_term_len: usize,
    min_score: f64,
    top_k: i64,
}
static RULES: LazyLock<Rules> = LazyLock::new(|| {
    serde_json::from_str(include_str!("chat_catalog/rules.json")).expect("canonical topic rules")
});
static CATALOG: LazyLock<Catalog> =
    LazyLock::new(|| Catalog::from_documents([&HOSTILE, &NEUTRAL, &PASSIVE], &STRUCTURES));

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Mob,
    Structure,
}
impl Kind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Mob => "mob",
            Self::Structure => "structure",
        }
    }
}
/// Rows are generated by this module, not by a model. The observed bit is only
/// an annotation; actual world grounding remains the existing planner's job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Hit {
    pub entry_id: String,
    pub kind: Kind,
    pub label_ja: String,
    pub score: f64,
    pub matched_terms: Vec<String>,
    pub observed: bool,
}
#[derive(Debug)]
struct Term {
    text: String,
    folded: String,
    entry_id: String,
    kind: Kind,
    field: String,
    length: usize,
    short_katakana: bool,
}
/// Full normalized entries are retained, including metadata not used for search.
/// The dictionary is immutable after construction. It owns no session or clock.
#[derive(Debug)]
pub struct Catalog {
    mobs: Map<String, Value>,
    structures: Map<String, Value>,
    terms: Vec<Term>,
}
pub fn catalog() -> &'static Catalog {
    &CATALOG
}
pub(crate) fn strip(s: &str) -> &str {
    s.trim_matches(crate::compat::is_python_whitespace)
}
/// Canonical kana-only folding: no NFKC, case folding or whitespace rewriting.
pub fn fold_kana(text: &str) -> String {
    crate::compat::fold_kana(text)
}
pub(crate) use crate::compat::json_truthy as truth;
// Catalogue fields are strings in the shipped schema. Scalar coercion also
// preserves the canonical legacy string-entry format and scalar aliases.
pub(crate) fn text(v: &Value) -> String {
    match v {
        Value::Null => "None".into(),
        Value::Bool(true) => "True".into(),
        Value::Bool(false) => "False".into(),
        Value::String(s) => s.clone(),
        Value::Array(a) => format!("[{}]", a.iter().map(repr).collect::<Vec<_>>().join(", ")),
        Value::Object(o) => format!(
            "{{{}}}",
            o.iter()
                .map(|(k, v)| format!("{}: {}", repr(&Value::String(k.clone())), repr(v)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Value::Number(n) => n.to_string(),
    }
}
fn repr(v: &Value) -> String {
    let Value::String(s) = v else {
        return text(v);
    };
    let quote = if s.contains('\'') && !s.contains('"') {
        '"'
    } else {
        '\''
    };
    let mut out = String::from(quote);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c == quote => {
                out.push('\\');
                out.push(c);
            }
            c if c.is_control() => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push(quote);
    out
}
fn label(entry: &Value, fallback: &str) -> String {
    entry
        .get("label")
        .filter(|v| truth(v))
        .map(text)
        .unwrap_or_else(|| fallback.into())
}
pub(crate) fn normalized_observation_id(s: &str) -> String {
    // Namespace removal intentionally precedes strip and lowercase, as in Python.
    strip(s.strip_prefix("minecraft:").unwrap_or(s)).to_lowercase()
}
impl Catalog {
    /// Trusted source documents in hostile/neutral/passive precedence. This is
    /// also the pure seam for canonical fixture tests; no runtime file scanning.
    pub fn from_documents(mob_sections: [&Value; 3], structures: &Value) -> Self {
        let mut mobs = Map::new();
        for section in mob_sections {
            let Some(section) = section.as_object() else {
                continue;
            };
            let wrapped = section.get("items").and_then(Value::as_object);
            for (id, payload) in wrapped.unwrap_or(section) {
                if wrapped.is_none()
                    && ["label", "items", "notes", "schema", "recommended_fields"]
                        .contains(&id.as_str())
                {
                    continue;
                }
                mobs.insert(
                    id.clone(),
                    if payload.is_object() {
                        payload.clone()
                    } else {
                        serde_json::json!({"label":text(payload)})
                    },
                );
            }
        }
        let mut flattened = Map::new();
        if let Some(groups) = structures["groups"].as_object() {
            for (group_id, group) in groups {
                let Some(group_map) = group.as_object() else {
                    continue;
                };
                let Some(entries) = group["structures"].as_object() else {
                    continue;
                };
                for (id, entry) in entries {
                    let Some(entry) = entry.as_object() else {
                        continue;
                    };
                    let mut entry = entry.clone();
                    let japanese = entry
                        .shift_remove("japanese")
                        .unwrap_or_else(|| Value::String(id.clone()));
                    entry.insert("label".into(), japanese);
                    entry.insert("group_id".into(), group_id.clone().into());
                    entry.insert("group_label".into(), group["label"].clone());
                    entry.insert("group_description".into(), group["description"].clone());
                    for (key, value) in group_map {
                        if !["label", "description", "structures"].contains(&key.as_str()) {
                            entry.insert(format!("group_{key}"), value.clone());
                        }
                    }
                    flattened.insert(id.clone(), Value::Object(entry));
                }
            }
        }
        let mut result = Self {
            mobs,
            structures: flattened,
            terms: vec![],
        };
        for (kind, entries) in [
            (Kind::Mob, &result.mobs),
            (Kind::Structure, &result.structures),
        ] {
            for (id, entry) in entries {
                let label = entry
                    .get("label")
                    .filter(|v| truth(v))
                    .or_else(|| entry.get("japanese").filter(|v| truth(v)))
                    .map(text)
                    .unwrap_or_default();
                let label_field = if kind == Kind::Mob {
                    "label"
                } else {
                    "structure_label"
                };
                add(&mut result.terms, &label, id, kind, label_field);
                if let Some(aliases) = entry["spoken_aliases"].as_array() {
                    for alias in aliases {
                        add(&mut result.terms, &text(alias), id, kind, "spoken_aliases");
                    }
                }
                if kind == Kind::Mob {
                    if let Some(poetic) = entry["poetic"].as_object() {
                        if let Some(role) = poetic.get("role").filter(|v| truth(v)) {
                            add(&mut result.terms, &text(role), id, kind, "role");
                        }
                        for key in [
                            "visual_tags",
                            "sound_tags",
                            "motion_tags",
                            "scene_tags",
                            "reaction_tags",
                            "comic_tags",
                        ] {
                            if let Some(values) = poetic.get(key).and_then(Value::as_array) {
                                for value in values {
                                    add(&mut result.terms, &text(value), id, kind, key);
                                }
                            }
                        }
                    }
                } else if truth(&entry["note"]) {
                    add(&mut result.terms, &text(&entry["note"]), id, kind, "note");
                }
            }
        }
        result.terms.sort_by(|a, b| {
            b.length
                .cmp(&a.length)
                .then_with(|| a.text.cmp(&b.text))
                .then_with(|| a.entry_id.cmp(&b.entry_id))
                .then_with(|| a.kind.as_str().cmp(b.kind.as_str()))
                .then_with(|| a.field.cmp(&b.field))
        });
        result
    }
    pub fn all_mob_entries(&self) -> &Map<String, Value> {
        &self.mobs
    }
    pub fn mob_entry(&self, id: &str) -> Option<&Value> {
        let normalized = strip(id).to_lowercase();
        let normalized = normalized.strip_prefix("minecraft:").unwrap_or(&normalized);
        if normalized.is_empty() {
            None
        } else {
            self.mobs.get(normalized)
        }
    }
    pub fn structure_entries(&self) -> &Map<String, Value> {
        &self.structures
    }
    /// Lossless audit projection of the canonical sorted index, including duplicates.
    pub fn term_rows(&self) -> Vec<(&str, &str, Kind, &str)> {
        self.terms
            .iter()
            .map(|r| {
                (
                    r.text.as_str(),
                    r.entry_id.as_str(),
                    r.kind,
                    r.field.as_str(),
                )
            })
            .collect()
    }
    pub fn find_topics(&self, query: &str, top_k: i64, min_score: f64) -> Vec<Hit> {
        let raw = strip(query);
        if raw.is_empty() {
            return vec![];
        }
        let folded = fold_kana(raw);
        let mut hits: Vec<Hit> = vec![];
        let mut positions = HashMap::new();
        for term in &self.terms {
            let raw_match = raw.contains(&term.text);
            if term.short_katakana && !raw_match {
                continue;
            }
            if !raw_match && !folded.contains(&term.folded) {
                continue;
            }
            let key = (term.kind, term.entry_id.as_str());
            let index = *positions.entry(key).or_insert_with(|| {
                // mob_entry normalizes lookup while preserving the original term ID.
                let entry = if term.kind == Kind::Mob {
                    self.mob_entry(&term.entry_id)
                } else {
                    self.structures.get(&term.entry_id)
                }
                .unwrap_or(&Value::Null);
                let pos = hits.len();
                hits.push(Hit {
                    entry_id: term.entry_id.clone(),
                    kind: term.kind,
                    label_ja: label(entry, &term.entry_id),
                    score: 0.0,
                    matched_terms: vec![],
                    observed: false,
                });
                pos
            });
            let hit = &mut hits[index];
            hit.score += RULES.field_weights.get(&term.field).copied().unwrap_or(2.0)
                * term.length.max(1) as f64;
            if !hit.matched_terms.contains(&term.text) {
                hit.matched_terms.push(term.text.clone());
            }
        }
        hits.retain(|h| h.score >= min_score);
        hits.sort_by(|a, b| {
            b.score
                .total_cmp(&a.score)
                .then_with(|| a.entry_id.cmp(&b.entry_id))
        });
        hits.truncate(top_k.max(0) as usize);
        hits
    }
    /// Exact narration contract: observations annotate the selected rows and
    /// cannot affect candidate score, order, or top-three membership.
    pub fn player_chat_topics(&self, query: &str, observed_ids: &[String]) -> Vec<Hit> {
        let observed: HashSet<String> = observed_ids
            .iter()
            .filter(|s| !strip(s).is_empty())
            .map(|s| normalized_observation_id(s))
            .collect();
        let mut hits = self.find_topics(query, RULES.top_k, RULES.min_score);
        for hit in &mut hits {
            hit.observed = observed.contains(&strip(&hit.entry_id).to_lowercase());
        }
        hits
    }
}
fn add(terms: &mut Vec<Term>, term: &str, id: &str, kind: Kind, field: &str) {
    let text = strip(term);
    let length = text.chars().count();
    if length < RULES.min_term_len
        || field == "note" && length > 24
        || field == "sound_tags" && length < 3
    {
        return;
    }
    terms.push(Term {
        text: text.into(),
        folded: fold_kana(text),
        entry_id: id.into(),
        kind,
        field: field.into(),
        length,
        short_katakana: length <= 2 && text.chars().all(|c| ('\u{30a0}'..='\u{30ff}').contains(&c)),
    });
}
/// Rendering uses every input hit, preserving order; only the matching-term
/// explanation is limited to four, exactly as the canonical formatter.
pub fn topic_hints(hits: &[Hit]) -> String {
    hits.iter()
        .map(|hit| {
            let terms = hit
                .matched_terms
                .iter()
                .take(4)
                .cloned()
                .collect::<Vec<_>>()
                .join("・");
            let observed = if hit.observed { "あり" } else { "なし" };
            let label = if hit.label_ja.is_empty() {
                &hit.entry_id
            } else {
                &hit.label_ja
            };
            let prefix = if hit.kind == Kind::Structure {
                "構造物"
            } else {
                "モブ"
            };
            if terms.is_empty() {
                format!("- [{prefix}] {label}: 観測: {observed}")
            } else {
                format!("- [{prefix}] {label}: マッチ「{terms}」。観測: {observed}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
