// Generated by scripts/generate_event_types.py; do not edit field declarations by hand.
use super::{EventTime, Validate, ensure, wire};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum AdapterCommandResultCommandType {
    #[serde(rename = "select_hotbar")]
    SelectHotbar,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum AdapterCommandResultStatus {
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "expired")]
    Expired,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CardinalDirection {
    #[serde(rename = "north")]
    North,
    #[serde(rename = "northeast")]
    Northeast,
    #[serde(rename = "east")]
    East,
    #[serde(rename = "southeast")]
    Southeast,
    #[serde(rename = "south")]
    South,
    #[serde(rename = "southwest")]
    Southwest,
    #[serde(rename = "west")]
    West,
    #[serde(rename = "northwest")]
    Northwest,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Certainty {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DistanceBand {
    #[serde(rename = "touching")]
    Touching,
    #[serde(rename = "very_close")]
    VeryClose,
    #[serde(rename = "close")]
    Close,
    #[serde(rename = "mid")]
    Mid,
    #[serde(rename = "far")]
    Far,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum EventName {
    #[serde(rename = "threat_approaching")]
    ThreatApproaching,
    #[serde(rename = "hostile_audio_detected")]
    HostileAudioDetected,
    #[serde(rename = "ambient_mob_detected")]
    AmbientMobDetected,
    #[serde(rename = "player_died")]
    PlayerDied,
    #[serde(rename = "hostile_defeated")]
    HostileDefeated,
    #[serde(rename = "creeper_detonated")]
    CreeperDetonated,
    #[serde(rename = "combat_ended")]
    CombatEnded,
    #[serde(rename = "status_snapshot")]
    StatusSnapshot,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum HorizontalDirection {
    #[serde(rename = "front")]
    Front,
    #[serde(rename = "front_right")]
    FrontRight,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "back_right")]
    BackRight,
    #[serde(rename = "back")]
    Back,
    #[serde(rename = "back_left")]
    BackLeft,
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "front_left")]
    FrontLeft,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum HostileOutcomeEvidence {
    #[serde(rename = "server_death_event")]
    ServerDeathEvent,
    #[serde(rename = "client_death_state")]
    ClientDeathState,
    #[serde(rename = "explosion_packet")]
    ExplosionPacket,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum HostileOutcomeOutcome {
    #[serde(rename = "player_kill")]
    PlayerKill,
    #[serde(rename = "explosion_death")]
    ExplosionDeath,
    #[serde(rename = "other_death")]
    OtherDeath,
    #[serde(rename = "creeper_detonation")]
    CreeperDetonation,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum HotbarSlotWeaponKind {
    #[serde(rename = "empty")]
    Empty,
    #[serde(rename = "sword")]
    Sword,
    #[serde(rename = "trident")]
    Trident,
    #[serde(rename = "axe")]
    Axe,
    #[serde(rename = "bow")]
    Bow,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "other")]
    Other,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PassiveMobTemperament {
    #[serde(rename = "passive")]
    Passive,
    #[serde(rename = "neutral")]
    Neutral,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PriorityHint {
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "urgent")]
    Urgent,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "background")]
    Background,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecentBlockBreakMaterial {
    #[serde(rename = "stone")]
    Stone,
    #[serde(rename = "earth")]
    Earth,
    #[serde(rename = "ore")]
    Ore,
    #[serde(rename = "other")]
    Other,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellDirectionEstimateBasis {
    #[serde(rename = "source_bearing")]
    SourceBearing,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellDirectionEstimateVertical {
    #[serde(rename = "above")]
    Above,
    #[serde(rename = "below")]
    Below,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationBasis {
    #[serde(rename = "smell_policy_v1")]
    SmellPolicyV1,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationCategory {
    #[serde(rename = "decay")]
    Decay,
    #[serde(rename = "compost")]
    Compost,
    #[serde(rename = "brewing")]
    Brewing,
    #[serde(rename = "swamp")]
    Swamp,
    #[serde(rename = "food")]
    Food,
    #[serde(rename = "flower")]
    Flower,
    #[serde(rename = "ink")]
    Ink,
    #[serde(rename = "rain_after")]
    RainAfter,
    #[serde(rename = "mixed")]
    Mixed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationSmellId {
    #[serde(rename = "zombie")]
    Zombie,
    #[serde(rename = "rotten_flesh")]
    RottenFlesh,
    #[serde(rename = "decay")]
    Decay,
    #[serde(rename = "composter")]
    Composter,
    #[serde(rename = "brewing_stand")]
    BrewingStand,
    #[serde(rename = "swamp")]
    Swamp,
    #[serde(rename = "raw_meat")]
    RawMeat,
    #[serde(rename = "raw_fish")]
    RawFish,
    #[serde(rename = "cooked_meat")]
    CookedMeat,
    #[serde(rename = "cooked_fish")]
    CookedFish,
    #[serde(rename = "cooking_meat")]
    CookingMeat,
    #[serde(rename = "cooking_fish")]
    CookingFish,
    #[serde(rename = "soup")]
    Soup,
    #[serde(rename = "cookie")]
    Cookie,
    #[serde(rename = "cake")]
    Cake,
    #[serde(rename = "bread")]
    Bread,
    #[serde(rename = "food")]
    Food,
    #[serde(rename = "ink_sac")]
    InkSac,
    #[serde(rename = "lily_of_the_valley")]
    LilyOfTheValley,
    #[serde(rename = "lilac")]
    Lilac,
    #[serde(rename = "peony")]
    Peony,
    #[serde(rename = "rose_bush")]
    RoseBush,
    #[serde(rename = "wither_rose")]
    WitherRose,
    #[serde(rename = "cactus_flower")]
    CactusFlower,
    #[serde(rename = "flowering_azalea")]
    FloweringAzalea,
    #[serde(rename = "allium")]
    Allium,
    #[serde(rename = "pitcher_plant")]
    PitcherPlant,
    #[serde(rename = "torchflower")]
    Torchflower,
    #[serde(rename = "open_eyeblossom")]
    OpenEyeblossom,
    #[serde(rename = "flower")]
    Flower,
    #[serde(rename = "rain_after")]
    RainAfter,
    #[serde(rename = "mixed")]
    Mixed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationSourceKind {
    #[serde(rename = "entity")]
    Entity,
    #[serde(rename = "block")]
    Block,
    #[serde(rename = "hotbar")]
    Hotbar,
    #[serde(rename = "dropped_item")]
    DroppedItem,
    #[serde(rename = "biome")]
    Biome,
    #[serde(rename = "mixed")]
    Mixed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationSpecificity {
    #[serde(rename = "source")]
    Source,
    #[serde(rename = "category")]
    Category,
    #[serde(rename = "mixed")]
    Mixed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "present")]
    Present,
    #[serde(rename = "suppressed")]
    Suppressed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationSuppressionReason {
    #[serde(rename = "rain")]
    Rain,
    #[serde(rename = "snow")]
    Snow,
    #[serde(rename = "thunder")]
    Thunder,
    #[serde(rename = "submerged")]
    Submerged,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SmellObservationValence {
    #[serde(rename = "pleasant")]
    Pleasant,
    #[serde(rename = "unpleasant")]
    Unpleasant,
    #[serde(rename = "mixed")]
    Mixed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceKind {
    #[serde(rename = "visual")]
    Visual,
    #[serde(rename = "auditory")]
    Auditory,
    #[serde(rename = "inferred")]
    Inferred,
    #[serde(rename = "system")]
    System,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimePhase {
    #[serde(rename = "morning")]
    Morning,
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "evening")]
    Evening,
    #[serde(rename = "night")]
    Night,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum VehicleStateActivity {
    #[serde(rename = "riding")]
    Riding,
    #[serde(rename = "moving")]
    Moving,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "rowing")]
    Rowing,
    #[serde(rename = "dashing")]
    Dashing,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum VerticalRelation {
    #[serde(rename = "above")]
    Above,
    #[serde(rename = "same")]
    Same,
    #[serde(rename = "below")]
    Below,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Weather {
    #[serde(rename = "clear")]
    Clear,
    #[serde(rename = "rain")]
    Rain,
    #[serde(rename = "thunder")]
    Thunder,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorldStateNearbyPortalEncounter {
    #[serde(rename = "appeared")]
    Appeared,
    #[serde(rename = "arrived")]
    Arrived,
    #[serde(rename = "observed")]
    Observed,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AdapterCommandResult {
    pub command_id: String,
    pub command_type: AdapterCommandResultCommandType,
    pub status: AdapterCommandResultStatus,
    pub executed_at: EventTime,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub selected_slot: Option<i64>,
    #[serde(default)]
    pub selected_item_id: Option<String>,
    #[serde(default = "default_adaptercommandresult_detail_code")]
    pub detail_code: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AmbientSound {
    pub r#type: String,
    #[serde(default)]
    pub source_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<MobIdentity>,
    #[serde(default)]
    pub sound_event: Option<String>,
    #[serde(default)]
    pub direction: Direction,
    #[serde(default)]
    pub distance_band: Option<DistanceBand>,
    #[serde(default = "default_ambientsound_certainty")]
    pub certainty: Certainty,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub heard_ago_ms: Option<i64>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AuditoryThreat {
    pub label: String,
    #[serde(default)]
    pub source_id: Option<String>,
    #[serde(default)]
    pub sound_event: Option<String>,
    #[serde(default)]
    pub direction: Direction,
    #[serde(default)]
    pub distance_band: Option<DistanceBand>,
    #[serde(default = "default_auditorythreat_certainty")]
    pub certainty: Certainty,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub spoken_name_allowed: bool,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub heard_ago_ms: Option<i64>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CombatState {
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub recent_damage_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub recent_hostile_visual_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub recent_hostile_audio_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub hostiles_within_7: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub hostiles_within_10: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub hostile_scan_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub hostiles_within_scan_ground: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub combat_active_hint: Option<bool>,
    #[serde(default)]
    pub hostile_outcomes: Option<Vec<HostileOutcome>>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_recently_hurt: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_defeat_confirmed: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_ranged_trap_active: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_nearby_iron_golem_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_experience_orb_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_end_crystal_bombardment_active: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_nearby_end_crystal_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_tnt_minecart_setup_active: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub warden_nearby_tnt_minecart_count: Option<i64>,
    #[serde(default)]
    pub dragon_phase: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub dragon_distance: Option<f64>,
    #[serde(default)]
    pub dragon_horizontal: Option<String>,
    #[serde(default)]
    pub dragon_vertical: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub dragon_defeat_confirmed: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub end_crystal_count: Option<i64>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for CombatState {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Direction {
    #[serde(default)]
    pub horizontal: Option<HorizontalDirection>,
    #[serde(default)]
    pub cardinal: Option<CardinalDirection>,
    #[serde(default)]
    pub vertical: Option<VerticalRelation>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for Direction {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DroppedItem {
    pub name: String,
    #[serde(deserialize_with = "wire::deserialize")]
    pub count: i64,
    #[serde(default = "default_droppeditem_entity_count")]
    #[serde(deserialize_with = "wire::deserialize")]
    pub entity_count: i64,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub age_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub block_item: bool,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub mining_related: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventDescriptor {
    pub name: EventName,
    pub source_kind: SourceKind,
    pub priority_hint: PriorityHint,
    pub certainty: Certainty,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HostileOutcome {
    pub r#type: String,
    pub entity_id: String,
    pub outcome: HostileOutcomeOutcome,
    pub evidence: HostileOutcomeEvidence,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HotbarSlot {
    #[serde(deserialize_with = "wire::deserialize")]
    pub slot: i64,
    #[serde(default)]
    pub item_id: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub count: i64,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub damage: i64,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub max_damage: i64,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub attack_damage: Option<f64>,
    #[serde(default = "default_hotbarslot_weapon_kind")]
    pub weapon_kind: HotbarSlotWeaponKind,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct HotbarState {
    #[serde(deserialize_with = "wire::deserialize")]
    pub selected_slot: i64,
    #[serde(default)]
    pub slots: Vec<HotbarSlot>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LookTarget {
    #[serde(default = "default_looktarget_kind")]
    pub kind: String,
    pub name: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<MobIdentity>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<MobEnvironment>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub distance: Option<f64>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MetaState {
    #[serde(default)]
    pub adapter_build: Option<String>,
    #[serde(default)]
    pub profile_name: Option<String>,
    #[serde(default)]
    pub call_name: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub debug: bool,
    #[serde(default)]
    pub death_cause: Option<String>,
    #[serde(default)]
    pub user_text: Option<String>,
    #[serde(default)]
    pub advancements: Vec<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for MetaState {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MobEnvironment {
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub touching_water: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub submerged_in_water: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub touching_water_or_rain: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub on_ground: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub on_fire: Option<bool>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for MobEnvironment {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MobIdentity {
    pub entity_id: String,
    #[serde(default)]
    pub custom_name: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub tamed: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NearbyResource {
    pub r#type: String,
    pub name: String,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub distance: Option<f64>,
    #[serde(default)]
    pub direction: Direction,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PassiveMob {
    pub r#type: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<MobIdentity>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<MobEnvironment>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub distance: Option<f64>,
    #[serde(default)]
    pub direction: Direction,
    #[serde(default = "default_passivemob_certainty")]
    pub certainty: Certainty,
    #[serde(default)]
    pub temperament: Option<PassiveMobTemperament>,
    #[serde(default)]
    pub caution_reason: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub is_baby: Option<bool>,
    #[serde(default)]
    pub profession: Option<String>,
    #[serde(default)]
    pub villager_type: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlayerState {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<MobEnvironment>,
    #[serde(default)]
    pub position: Position,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub yaw: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub pitch: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub health: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub hunger: Option<i64>,
    #[serde(default)]
    pub dimension: Option<String>,
    #[serde(default)]
    pub held_item: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub block_breaking_active: Option<bool>,
    #[serde(default)]
    pub hotbar: Option<HotbarState>,
    #[serde(default)]
    pub vehicle: Option<VehicleState>,
    #[serde(default)]
    pub active_status_effects: Vec<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for PlayerState {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Position {
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub x: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub y: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub z: Option<f64>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for Position {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RecentBlockBreak {
    pub name: String,
    #[serde(default = "default_recentblockbreak_material")]
    pub material: RecentBlockBreakMaterial,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub age_ms: i64,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SmellDirectionEstimate {
    #[serde(default)]
    pub cardinal: Option<CardinalDirection>,
    #[serde(default)]
    pub vertical: Option<SmellDirectionEstimateVertical>,
    #[serde(default = "default_smelldirectionestimate_basis")]
    pub basis: SmellDirectionEstimateBasis,
}
impl Default for SmellDirectionEstimate {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SmellObservation {
    pub status: SmellObservationStatus,
    #[serde(default)]
    pub smell_id: Option<SmellObservationSmellId>,
    #[serde(default)]
    pub category: Option<SmellObservationCategory>,
    #[serde(default)]
    pub valence: Option<SmellObservationValence>,
    #[serde(default)]
    pub source_kind: Option<SmellObservationSourceKind>,
    #[serde(default)]
    pub specificity: Option<SmellObservationSpecificity>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub effective_strength: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub temperature_modifier: i64,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub rain_after_active: bool,
    #[serde(default)]
    pub suppression_reason: Option<SmellObservationSuppressionReason>,
    #[serde(default)]
    pub direction_estimate: Option<SmellDirectionEstimate>,
    #[serde(default = "default_smellobservation_basis")]
    pub basis: SmellObservationBasis,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct VehicleState {
    pub vehicle_id: String,
    #[serde(default = "default_vehiclestate_activity")]
    pub activity: VehicleStateActivity,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub controlling: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct VisualThreat {
    pub r#type: String,
    #[serde(default)]
    pub entity_id: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<MobIdentity>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub environment: Option<MobEnvironment>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub distance: Option<f64>,
    #[serde(default)]
    pub direction: Direction,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub approaching: bool,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub fuse_active: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub on_fire: bool,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub in_water: bool,
    #[serde(default = "default_visualthreat_certainty")]
    pub certainty: Certainty,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WorldState {
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub time_of_day: Option<i64>,
    #[serde(default)]
    pub time_phase: Option<TimePhase>,
    #[serde(default)]
    pub weather: Option<Weather>,
    #[serde(default)]
    pub biome: Option<String>,
    #[serde(default)]
    pub structure: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub local_light: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub sky_visible: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub surface_y: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub depth_below_surface: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub ceiling_height: Option<f64>,
    #[serde(default)]
    pub overhead_cover_type: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub is_submerged: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub submerged_depth_blocks: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub air_supply: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_door_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub open_door_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_window_present: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_bed_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_sleeping_people_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub drafty_opening_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub respawn_point_set: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub respawn_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub cardinal_wall_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub double_height_open_side_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub safe_zone_with_door: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub enclosure_score: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub connected_dark_volume: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearest_dark_spawn_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub danger_darkness_score: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_light_source_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearest_light_source_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_damaging_light_source_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearest_damaging_light_source_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub standing_on_magma_block: Option<bool>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_firefly_bush_count: Option<i64>,
    #[serde(default)]
    pub ominous_sound_kind: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub ominous_sound_recent_ms: Option<i64>,
    #[serde(default)]
    pub boss_omen_kind: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub rain_sound_recent_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub thunder_sound_recent_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_lightning_strike_recent_ms: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_lightning_strike_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub ender_eye_launch_recent_ms: Option<i64>,
    #[serde(default)]
    pub nearby_portal_type: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_portal_distance: Option<f64>,
    #[serde(default)]
    pub nearby_portal_encounter: Option<WorldStateNearbyPortalEncounter>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub visible_villager_count: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub nearby_end_portal_frame_distance: Option<f64>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub game_paused: Option<bool>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
impl Default for WorldState {
    fn default() -> Self {
        serde_json::from_str("{}").expect("model defaults")
    }
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventData {
    pub schema_version: String,
    #[serde(default = "default_eventdata_game")]
    pub game: String,
    pub adapter: String,
    pub observed_at: EventTime,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub sequence: Option<i64>,
    pub event: EventDescriptor,
    #[serde(default)]
    pub player: PlayerState,
    #[serde(default)]
    pub world: WorldState,
    #[serde(default)]
    pub visual_threats: Vec<VisualThreat>,
    #[serde(default)]
    pub auditory_threats: Vec<AuditoryThreat>,
    #[serde(default)]
    pub smell_observation: Option<SmellObservation>,
    #[serde(default)]
    pub ambient_sounds: Vec<AmbientSound>,
    #[serde(default)]
    pub passive_mobs: Vec<PassiveMob>,
    #[serde(default)]
    #[serde(deserialize_with = "wire::deserialize")]
    pub inventory: BTreeMap<String, i64>,
    #[serde(default)]
    pub nearby_resources: Vec<NearbyResource>,
    #[serde(default)]
    pub dropped_items: Vec<DroppedItem>,
    #[serde(default)]
    pub recent_block_breaks: Vec<RecentBlockBreak>,
    #[serde(default)]
    pub look_target: Option<LookTarget>,
    #[serde(default)]
    pub combat: CombatState,
    #[serde(default)]
    pub meta: MetaState,
    #[serde(default)]
    pub command_results: Vec<AdapterCommandResult>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}
fn default_adaptercommandresult_detail_code() -> String {
    "".into()
}
fn default_ambientsound_certainty() -> Certainty {
    Certainty::Medium
}
fn default_auditorythreat_certainty() -> Certainty {
    Certainty::Low
}
fn default_droppeditem_entity_count() -> i64 {
    1
}
fn default_hotbarslot_weapon_kind() -> HotbarSlotWeaponKind {
    HotbarSlotWeaponKind::Empty
}
fn default_looktarget_kind() -> String {
    "block".into()
}
fn default_passivemob_certainty() -> Certainty {
    Certainty::High
}
fn default_recentblockbreak_material() -> RecentBlockBreakMaterial {
    RecentBlockBreakMaterial::Other
}
fn default_smelldirectionestimate_basis() -> SmellDirectionEstimateBasis {
    SmellDirectionEstimateBasis::SourceBearing
}
fn default_smellobservation_basis() -> SmellObservationBasis {
    SmellObservationBasis::SmellPolicyV1
}
fn default_vehiclestate_activity() -> VehicleStateActivity {
    VehicleStateActivity::Riding
}
fn default_visualthreat_certainty() -> Certainty {
    Certainty::High
}
fn default_eventdata_game() -> String {
    "minecraft-java".into()
}
impl Validate for AdapterCommandResult {
    fn validate(&self) -> Result<(), String> {
        ensure(
            (self.command_id).chars().count() >= 1,
            "AdapterCommandResult.command_id: minLength 1",
        )?;
        if let Some(value) = &self.selected_slot {
            ensure(*value >= 0, "AdapterCommandResult.selected_slot: minimum 0")?;
            ensure(*value <= 8, "AdapterCommandResult.selected_slot: maximum 8")?;
        }
        ensure(
            (self.detail_code).chars().count() <= 80,
            "AdapterCommandResult.detail_code: maxLength 80",
        )?;
        Ok(())
    }
}
impl Validate for AmbientSound {
    fn validate(&self) -> Result<(), String> {
        self.identity.validate()?;
        self.direction.validate()?;
        if let Some(value) = &self.heard_ago_ms {
            ensure(*value >= 0, "AmbientSound.heard_ago_ms: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for AuditoryThreat {
    fn validate(&self) -> Result<(), String> {
        self.direction.validate()?;
        if let Some(value) = &self.heard_ago_ms {
            ensure(*value >= 0, "AuditoryThreat.heard_ago_ms: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for CombatState {
    fn validate(&self) -> Result<(), String> {
        if let Some(value) = &self.recent_damage_ms {
            ensure(*value >= 0, "CombatState.recent_damage_ms: minimum 0")?;
        }
        if let Some(value) = &self.recent_hostile_visual_ms {
            ensure(
                *value >= 0,
                "CombatState.recent_hostile_visual_ms: minimum 0",
            )?;
        }
        if let Some(value) = &self.recent_hostile_audio_ms {
            ensure(
                *value >= 0,
                "CombatState.recent_hostile_audio_ms: minimum 0",
            )?;
        }
        if let Some(value) = &self.hostiles_within_7 {
            ensure(*value >= 0, "CombatState.hostiles_within_7: minimum 0")?;
        }
        if let Some(value) = &self.hostiles_within_10 {
            ensure(*value >= 0, "CombatState.hostiles_within_10: minimum 0")?;
        }
        if let Some(value) = &self.hostile_scan_distance {
            ensure(
                *value >= 0.0,
                "CombatState.hostile_scan_distance: minimum 0",
            )?;
        }
        if let Some(value) = &self.hostiles_within_scan_ground {
            ensure(
                *value >= 0,
                "CombatState.hostiles_within_scan_ground: minimum 0",
            )?;
        }
        self.hostile_outcomes.validate()?;
        if let Some(value) = &self.warden_nearby_iron_golem_count {
            ensure(
                *value >= 0,
                "CombatState.warden_nearby_iron_golem_count: minimum 0",
            )?;
        }
        if let Some(value) = &self.nearby_experience_orb_count {
            ensure(
                *value >= 0,
                "CombatState.nearby_experience_orb_count: minimum 0",
            )?;
        }
        if let Some(value) = &self.warden_nearby_end_crystal_count {
            ensure(
                *value >= 0,
                "CombatState.warden_nearby_end_crystal_count: minimum 0",
            )?;
        }
        if let Some(value) = &self.warden_nearby_tnt_minecart_count {
            ensure(
                *value >= 0,
                "CombatState.warden_nearby_tnt_minecart_count: minimum 0",
            )?;
        }
        if let Some(value) = &self.end_crystal_count {
            ensure(*value >= 0, "CombatState.end_crystal_count: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for Direction {
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
impl Validate for DroppedItem {
    fn validate(&self) -> Result<(), String> {
        ensure(self.count >= 1, "DroppedItem.count: minimum 1")?;
        ensure(
            self.entity_count >= 1,
            "DroppedItem.entity_count: minimum 1",
        )?;
        if let Some(value) = &self.distance {
            ensure(*value >= 0.0, "DroppedItem.distance: minimum 0")?;
        }
        if let Some(value) = &self.age_ms {
            ensure(*value >= 0, "DroppedItem.age_ms: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for EventDescriptor {
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
impl Validate for HostileOutcome {
    fn validate(&self) -> Result<(), String> {
        ensure(
            (self.entity_id).chars().count() >= 1,
            "HostileOutcome.entity_id: minLength 1",
        )?;
        ensure(
            (self.entity_id).chars().count() <= 80,
            "HostileOutcome.entity_id: maxLength 80",
        )?;
        Ok(())
    }
}
impl Validate for HotbarSlot {
    fn validate(&self) -> Result<(), String> {
        ensure(self.slot >= 0, "HotbarSlot.slot: minimum 0")?;
        ensure(self.slot <= 8, "HotbarSlot.slot: maximum 8")?;
        ensure(self.count >= 0, "HotbarSlot.count: minimum 0")?;
        ensure(self.damage >= 0, "HotbarSlot.damage: minimum 0")?;
        ensure(self.max_damage >= 0, "HotbarSlot.max_damage: minimum 0")?;
        if let Some(value) = &self.attack_damage {
            ensure(*value >= 0.0, "HotbarSlot.attack_damage: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for HotbarState {
    fn validate(&self) -> Result<(), String> {
        ensure(
            self.selected_slot >= 0,
            "HotbarState.selected_slot: minimum 0",
        )?;
        ensure(
            self.selected_slot <= 8,
            "HotbarState.selected_slot: maximum 8",
        )?;
        ensure((self.slots).len() <= 9, "HotbarState.slots: maxItems 9")?;
        self.slots.validate()?;
        self.validate_semantics()?;
        Ok(())
    }
}
impl Validate for LookTarget {
    fn validate(&self) -> Result<(), String> {
        self.identity.validate()?;
        self.environment.validate()?;
        Ok(())
    }
}
impl Validate for MetaState {
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
impl Validate for MobEnvironment {
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
impl Validate for MobIdentity {
    fn validate(&self) -> Result<(), String> {
        ensure(
            (self.entity_id).chars().count() >= 1,
            "MobIdentity.entity_id: minLength 1",
        )?;
        ensure(
            (self.entity_id).chars().count() <= 64,
            "MobIdentity.entity_id: maxLength 64",
        )?;
        if let Some(value) = &self.custom_name {
            ensure(
                (value).chars().count() <= 64,
                "MobIdentity.custom_name: maxLength 64",
            )?;
        }
        Ok(())
    }
}
impl Validate for NearbyResource {
    fn validate(&self) -> Result<(), String> {
        self.direction.validate()?;
        Ok(())
    }
}
impl Validate for PassiveMob {
    fn validate(&self) -> Result<(), String> {
        self.identity.validate()?;
        self.environment.validate()?;
        self.direction.validate()?;
        Ok(())
    }
}
impl Validate for PlayerState {
    fn validate(&self) -> Result<(), String> {
        self.environment.validate()?;
        self.position.validate()?;
        self.hotbar.validate()?;
        self.vehicle.validate()?;
        Ok(())
    }
}
impl Validate for Position {
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
impl Validate for RecentBlockBreak {
    fn validate(&self) -> Result<(), String> {
        ensure(self.age_ms >= 0, "RecentBlockBreak.age_ms: minimum 0")?;
        Ok(())
    }
}
impl Validate for SmellDirectionEstimate {
    fn validate(&self) -> Result<(), String> {
        self.validate_semantics()?;
        Ok(())
    }
}
impl Validate for SmellObservation {
    fn validate(&self) -> Result<(), String> {
        if let Some(value) = &self.effective_strength {
            ensure(
                *value >= 1,
                "SmellObservation.effective_strength: minimum 1",
            )?;
            ensure(
                *value <= 12,
                "SmellObservation.effective_strength: maximum 12",
            )?;
        }
        ensure(
            self.temperature_modifier >= -7,
            "SmellObservation.temperature_modifier: minimum -7",
        )?;
        ensure(
            self.temperature_modifier <= 2,
            "SmellObservation.temperature_modifier: maximum 2",
        )?;
        self.direction_estimate.validate()?;
        self.validate_semantics()?;
        Ok(())
    }
}
impl Validate for VehicleState {
    fn validate(&self) -> Result<(), String> {
        ensure(
            (self.vehicle_id).chars().count() >= 1,
            "VehicleState.vehicle_id: minLength 1",
        )?;
        Ok(())
    }
}
impl Validate for VisualThreat {
    fn validate(&self) -> Result<(), String> {
        self.identity.validate()?;
        self.environment.validate()?;
        self.direction.validate()?;
        Ok(())
    }
}
impl Validate for WorldState {
    fn validate(&self) -> Result<(), String> {
        if let Some(value) = &self.depth_below_surface {
            ensure(*value >= 0, "WorldState.depth_below_surface: minimum 0")?;
        }
        if let Some(value) = &self.visible_villager_count {
            ensure(*value >= 0, "WorldState.visible_villager_count: minimum 0")?;
        }
        Ok(())
    }
}
impl Validate for EventData {
    fn validate(&self) -> Result<(), String> {
        if let Some(value) = &self.sequence {
            ensure(*value >= 0, "EventData.sequence: minimum 0")?;
        }
        self.event.validate()?;
        self.player.validate()?;
        self.world.validate()?;
        self.visual_threats.validate()?;
        self.auditory_threats.validate()?;
        self.smell_observation.validate()?;
        self.ambient_sounds.validate()?;
        self.passive_mobs.validate()?;
        self.nearby_resources.validate()?;
        ensure(
            (self.dropped_items).len() <= 32,
            "EventData.dropped_items: maxItems 32",
        )?;
        self.dropped_items.validate()?;
        ensure(
            (self.recent_block_breaks).len() <= 32,
            "EventData.recent_block_breaks: maxItems 32",
        )?;
        self.recent_block_breaks.validate()?;
        self.look_target.validate()?;
        self.combat.validate()?;
        self.meta.validate()?;
        ensure(
            (self.command_results).len() <= 32,
            "EventData.command_results: maxItems 32",
        )?;
        self.command_results.validate()?;
        Ok(())
    }
}
