'use strict';
const $ = id => document.getElementById(id);
const parts = ['base','normal','tension','grounding','dialogue','choice_contract'];
let state, loadedCandidate, prepared, selected = new Set(), renderedKey='';
const el = (tag,text,cls) => {const n=document.createElement(tag); if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const fmt = (v,d=1) => v==null?'未測定':Number(v).toFixed(d);
const gb = v => v==null?'未測定':(v/1e9).toFixed(2)+' GB';
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||r.status);return data;}
function message(e){$('message').textContent=e instanceof Error?e.message:e;}
function tab(id){document.querySelectorAll('.tab').forEach(n=>n.classList.toggle('active',n.id===id));document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===id));}
document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>tab(n.dataset.tab));
function options(node,items){node.replaceChildren(...items.map(c=>{const n=el('option',c.title||c.id);n.value=c.id;return n;}));}
function checkboxes(node,items,prefix,checked){node.replaceChildren(...items.map(c=>{const l=el('label');const i=el('input');i.type='checkbox';i.name=prefix;i.value=c.id;i.checked=checked.includes(c.id);l.append(i,document.createTextNode(c.title+(c.backend==='mlx'&&!c.available?'（キャッシュなし）':'')));return l;}));}
async function refresh(initial=false){state=await api('/api/state');state.runs.sort((a,b)=>b.manifest.created_at.localeCompare(a.manifest.created_at));$('status').textContent=state.manager.running?'試験中 · 結果を順次保存':'待機中';if(state.manager.error)message(state.manager.error);if(initial){options($('candidate-select'),state.candidates);options($('suite'),state.suites);$('suite').value='mobs15-entity-context';checkboxes($('candidate-checks'),state.candidates,'candidates',['canonical']);checkboxes($('model-checks'),state.models,'models',['http-current']);loadCandidate('canonical');const linked=new URLSearchParams(location.search).getAll('run');if(linked.length){linked.filter(id=>state.runs.some(r=>r.manifest.id===id)).forEach(id=>selected.add(id));}else{state.runs.filter(r=>r.manifest.id.startsWith('import-')&&r.manifest.candidate.id==='previous-probe').slice(0,2).forEach(r=>selected.add(r.manifest.id));}}if(!initial){const current=$('candidate-select').value;options($('candidate-select'),state.candidates);$('candidate-select').value=current;const chosen=Array.from(document.querySelectorAll('input[name=candidates]:checked')).map(n=>n.value);checkboxes($('candidate-checks'),state.candidates,'candidates',chosen);}renderRuns();renderNotes();const key=JSON.stringify(state.runs.map(r=>[r.manifest.id,r.manifest.status,r.summary.count]))+Array.from(selected);if(key!==renderedKey){await compare();renderedKey=key;}}
function renderRuns(){const filter=$('filter').value.toLowerCase();$('run-list').replaceChildren(...state.runs.filter(r=>JSON.stringify([r.manifest.candidate.title,r.manifest.model.title]).toLowerCase().includes(filter)).map(r=>{const m=r.manifest,s=r.summary,l=el('label',undefined,'run-card'),i=el('input');i.type='checkbox';i.checked=selected.has(m.id);i.onchange=()=>{i.checked?selected.add(m.id):selected.delete(m.id);compare().catch(message);};l.append(i,el('strong',m.candidate.title),el('span',m.model.title+(m.model.backend==='mlx'?'［条件外の参考］':'')),el('span',suiteTitle(m)),el('span',m.status+' · '+s.count+'/'+m.case_count+' 件'),el('span','JSON '+s.format_ok+'/'+s.format_checked+' · 注目語 '+s.watch_cases+'件'),el('span','平均 '+fmt(s.mean_elapsed_ms,0)+' ms · RSS '+gb(s.peak_rss_bytes)));return l;}));}
function suiteTitle(manifest){return manifest.suite?.title||manifest.suite?.id||'過去の取り込み試験';}
function detail(title,value){const d=el('details');d.append(el('summary',title),el('pre',typeof value==='string'?value:JSON.stringify(value,null,2)));return d;}
async function compare(){const ids=Array.from(selected);if(!ids.length){$('compare').replaceChildren(el('p','上のカードを選んで比較してください。'));return;}const runs=await Promise.all(ids.map(id=>api('/api/run?id='+encodeURIComponent(id))));const table=el('table'),head=el('tr');head.append(el('th','ケース'));for(const r of runs){const th=el('th');th.append(el('strong',r.manifest.candidate.title),el('div',r.manifest.model.title+(r.manifest.model.backend==='mlx'?'［8080との比較対象外］':'')),el('div',suiteTitle(r.manifest)),el('div','平均CPU '+fmt(r.summary.mean_cpu_percent)+'% · RSS '+gb(r.summary.peak_rss_bytes)),el('div','MLX確保 '+gb(r.summary.peak_mlx_bytes)));const a=el('a','保存用レポート');a.href='/report?id='+encodeURIComponent(r.manifest.id);a.target='_blank';th.append(a,detail('試験条件 / 測定範囲',r.manifest));head.append(th);}table.append(head);const cases=new Map();for(const r of runs)for(const q of r.requests)cases.set(q.case_id+':'+q.repeat,q);for(const [key,q]of cases){const tr=el('tr');tr.append(el('th',q.label+'\n'+(q.group||'')+' #'+q.repeat));for(const r of runs){const cell=el('td'),row=r.results.find(x=>x.case_id+':'+x.repeat===key),request=r.requests.find(x=>x.case_id+':'+x.repeat===key);if(!row){cell.append(el('div',request?'待機中':'対象外'));if(request)cell.append(detail('送信全文',request.payload));}else{cell.append(el('div',row.error||row.speech||'（沈黙）',row.error?'speech error':'speech'));for(const hit of Object.keys(row.watch_hits||{}))cell.append(el('span',hit,'flag'));const m=row.metrics||{};cell.append(el('div',fmt(m.elapsed_ms,0)+' ms / TTFT '+fmt(m.ttft_ms,0)+' ms / '+fmt(m.tokens_per_second)+' tok/s\nCPU '+fmt(m.cpu_percent)+'% / RSS '+gb(m.peak_rss_bytes),'metrics'),detail('送信全文',request?.payload),detail('返答原文 / 検査',row));const b=el('button','メモ');b.onclick=()=>{$('note-run').value=r.manifest.id;$('note-case').value=q.case_id;tab('discussion');};cell.append(b);}tr.append(cell);}table.append(tr);}$('compare').replaceChildren(table);}
function loadCandidate(id){loadedCandidate=state.candidates.find(c=>c.id===id)||state.candidates[0];$('candidate-select').value=loadedCandidate.id;$('candidate-id').value=loadedCandidate.id==='canonical'?'my-candidate':loadedCandidate.id;$('candidate-title').value=loadedCandidate.title;$('author').value=loadedCandidate.author||'User';$('hypothesis').value=loadedCandidate.hypothesis||'';$('body-mode').value=loadedCandidate.body_mode;$('response-format').value=loadedCandidate.response_format;$('components').replaceChildren(...parts.map(p=>{const l=el('label',p==='normal'?'normal（平時）':p),t=el('textarea');t.id='part-'+p;t.value=loadedCandidate.components[p];l.append(t);return l;}));}
$('candidate-select').onchange=e=>loadCandidate(e.target.value);
$('save').onclick=async()=>{try{const id=$('candidate-id').value;const candidate={schema_version:1,id,title:$('candidate-title').value,author:$('author').value,hypothesis:$('hypothesis').value,body_mode:$('body-mode').value,response_format:$('response-format').value,components:Object.fromEntries(parts.map(p=>[p,$('part-'+p).value]))};const saved=await api('/api/candidate',{candidate,expected_etag:id===loadedCandidate.id?loadedCandidate.etag:null});await refresh();options($('candidate-select'),state.candidates);checkboxes($('candidate-checks'),state.candidates,'candidates',[saved.id]);loadCandidate(saved.id);message('候補を保存しました。次の試験から使用できます。');}catch(e){message(e);}};
$('prepare').onclick=async()=>{try{const checked=name=>Array.from(document.querySelectorAll('input[name='+name+']:checked')).map(n=>n.value);const candidate_ids=checked('candidates'),model_ids=checked('models');if(!candidate_ids.length||!model_ids.length)throw Error('候補とモデルを選んでください。');const pid=$('pid').value;prepared=await api('/api/prepare',{candidate_ids,model_ids,suite_id:$('suite').value,model_overrides:pid?{'http-current':{metrics_pid:Number(pid)}}:{},settings:{temperature:Number($('temperature').value),max_tokens:Number($('tokens').value),repeats:Number($('repeats').value),seed:$('seed').value===''?null:Number($('seed').value),top_p:$('top-p').value===''?null:Number($('top-p').value),stream:$('stream').checked,enable_thinking:$('thinking').checked}});$('prepared').replaceChildren(detail('固定した試験のID',prepared));$('start').disabled=false;selected=new Set(prepared.runs);await refresh();message('準備完了。「結果を比較」で送信全文を確認できます。実行するとこの内容を使用します。');}catch(e){message(e);}};
$('start').onclick=async()=>{try{await api('/api/start',{batch_id:prepared.id});$('start').disabled=true;tab('results');await refresh();message('試験を開始しました。');}catch(e){message(e);}};
$('cancel').onclick=async()=>{try{message((await api('/api/cancel',{})).message);}catch(e){message(e);}};
function renderNotes(){$('notes').replaceChildren(...state.notes.slice().reverse().map(n=>{const d=el('div',undefined,'note');d.append(el('strong',n.author+' · '+n.verdict+' · '+n.created_at),el('div',(n.run_id||'全体')+(n.case_id?' / '+n.case_id:''),'muted'),el('div',n.body));return d;}));}
$('add-note').onclick=async()=>{try{await api('/api/note',{author:$('note-author').value,run_id:$('note-run').value||null,case_id:$('note-case').value||null,verdict:$('verdict').value,body:$('note-body').value});$('note-body').value='';await refresh();message('メモを保存しました。');}catch(e){message(e);}};
$('filter').oninput=renderRuns;$('refresh').onclick=()=>refresh().catch(message);
refresh(true).catch(message);setInterval(()=>refresh().catch(message),4000);
